import 'server-only';

// ─────────────────────────────────────────────────────────────────────────────
// What each kind of job does, and how its failure is read.
//
// A handler runs the same service the screen runs, in a transaction of its
// own, so a retry is exactly the submission a person would have made. What it
// throws decides what happens next: an outage waits and tries again, a refusal
// stops, and "already done" counts as done, because somebody got there by hand
// while the retry was waiting.
// ─────────────────────────────────────────────────────────────────────────────

import { transaction } from '../db';
import { ApiError } from '../http';
import { logAudit } from '../audit';
import { registerInvoice } from '../integrations/gst/einvoice-service';
import { generateEwayBill, type EwayBillDocument, type TransportInput } from '../integrations/gst/eway-service';
import type { ClaimedJob, JobOutcome } from './queue';

export type JobHandler = (job: ClaimedJob) => Promise<unknown>;

const RETRY_ACTOR = 'Automatic retry';

export const HANDLERS: Record<string, JobHandler> = {
  'einvoice.register': async (job) => {
    const invoiceId = Number(job.payload.invoiceId);
    const result = await transaction((trx) => registerInvoice(trx, job.org_id, invoiceId));
    await logAudit({
      orgId: job.org_id,
      actorUserId: job.created_by_user_id,
      actorName: RETRY_ACTOR,
      action: 'approve',
      targetType: 'einvoice',
      targetId: invoiceId,
      detail: `IRN registered via ${result.provider} on automatic retry ${job.attempts}: ${result.irn.slice(0, 16)}…`,
    });
    return { irn: result.irn };
  },

  'ewb.generate': async (job) => {
    const doc = job.payload.doc as EwayBillDocument;
    const transport = job.payload.transport as TransportInput;
    const result = await transaction((trx) =>
      generateEwayBill(trx, job.org_id, doc, transport, { userId: job.created_by_user_id }),
    );
    await logAudit({
      orgId: job.org_id,
      actorUserId: job.created_by_user_id,
      actorName: RETRY_ACTOR,
      action: 'approve',
      targetType: 'eway_bill',
      targetId: doc.id,
      detail: `E-way bill ${result.ewayBillNo} generated via ${result.provider} on automatic retry ${job.attempts}`,
    });
    return { ewayBillNo: result.ewayBillNo };
  },
};

/** Run a job, and say what should happen to it next. */
export async function runJobHandler(job: ClaimedJob, handlers: Record<string, JobHandler> = HANDLERS): Promise<JobOutcome> {
  const handler = handlers[job.kind];
  if (!handler) return { kind: 'fail', error: `Nothing in this app runs jobs of kind "${job.kind}".` };

  try {
    return { kind: 'done', result: await handler(job) };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (err instanceof ApiError && err.code === 'portal_unavailable') return { kind: 'retry', error: message };
    // Registered or generated by hand while the retry waited: its purpose is served.
    if (err instanceof ApiError && err.status === 409 && /already has/i.test(message)) {
      return { kind: 'done', result: { note: message } };
    }
    return { kind: 'fail', error: message };
  }
}
