/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Accounts {
  code: string;
  created_at: Generated<Date>;
  description: string | null;
  id: Generated<number>;
  is_active: Generated<number>;
  is_system: Generated<number>;
  name: string;
  org_id: number;
  parent_id: number | null;
  subtype: string | null;
  type: "asset" | "equity" | "expense" | "income" | "liability";
  updated_at: Generated<Date>;
}

export interface ApiTokens {
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  expires_at: Date | null;
  id: Generated<number>;
  last_used_at: Date | null;
  name: string;
  org_id: number;
  revoked_at: Date | null;
  scopes: Json;
  token_hash: string;
  token_prefix: string;
}

export interface ApprovalRules {
  approver_role: Generated<"accountant" | "admin" | "sales" | "staff" | "viewer">;
  created_at: Generated<Date>;
  document_type: string;
  id: Generated<number>;
  is_active: Generated<number>;
  org_id: number;
  threshold_amount: Generated<Decimal>;
}

export interface AuditLog {
  action: string;
  actor_name: string | null;
  actor_user_id: number | null;
  created_at: Generated<Date>;
  detail: string | null;
  id: Generated<number>;
  ip: string | null;
  org_id: number;
  payload: Json | null;
  target_id: string | null;
  target_label: string | null;
  target_type: string | null;
  user_agent: string | null;
}

export interface BankAccounts {
  account_last4: string | null;
  bank_name: string | null;
  created_at: Generated<Date>;
  feed_connected: Generated<number>;
  id: Generated<number>;
  ifsc: string | null;
  is_active: Generated<number>;
  is_primary: Generated<number>;
  kind: Generated<"bank" | "card" | "cash" | "clearing" | "wallet">;
  ledger_account_id: number;
  name: string;
  opening_balance: Generated<Decimal>;
  opening_date: ColumnType<string | null, string | null, string | null>;
  org_id: number;
  updated_at: Generated<Date>;
}

export interface BankRules {
  action_account_id: number | null;
  auto_confirm: Generated<number>;
  bank_account_id: number | null;
  conditions: Json;
  contact_id: number | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  is_active: Generated<number>;
  name: string;
  org_id: number;
  priority: Generated<number>;
  updated_at: Generated<Date>;
}

export interface BankStatementImports {
  bank_account_id: number;
  created_at: Generated<Date>;
  file_id: number | null;
  filename: string;
  id: Generated<number>;
  imported_by_user_id: number | null;
  org_id: number;
  period_from: ColumnType<string | null, string | null, string | null>;
  period_to: ColumnType<string | null, string | null, string | null>;
  rows_duplicate: Generated<number>;
  rows_imported: Generated<number>;
  rows_total: Generated<number>;
}

export interface BankTransactions {
  applied_rule_id: number | null;
  bank_account_id: number;
  created_at: Generated<Date>;
  dedupe_hash: string;
  deposit: Generated<Decimal>;
  id: Generated<number>;
  import_batch_id: number | null;
  matched_at: Date | null;
  matched_by_user_id: number | null;
  matched_id: number | null;
  matched_type: string | null;
  narration: string;
  org_id: number;
  reference: string | null;
  running_balance: Decimal | null;
  status: Generated<"excluded" | "manually_added" | "matched" | "unmatched">;
  txn_date: ColumnType<string, string, string>;
  withdrawal: Generated<Decimal>;
}

export interface BankTransfers {
  amount: Decimal;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  from_bank_account_id: number;
  id: Generated<number>;
  journal_entry_id: number | null;
  org_id: number;
  reference: string | null;
  to_bank_account_id: number;
  transfer_date: ColumnType<string, string, string>;
}

export interface BillLines {
  account_id: number | null;
  bill_id: number;
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  description: string | null;
  discount_pct: Generated<Decimal>;
  gst_rate_pct: Generated<Decimal>;
  hsn_sac: string | null;
  id: Generated<number>;
  igst: Generated<Decimal>;
  itc_eligibility: Generated<"capital_goods" | "eligible" | "ineligible">;
  item_id: number | null;
  line_no: number;
  line_total: Generated<Decimal>;
  org_id: number;
  qty: Generated<Decimal>;
  rate: Generated<Decimal>;
  sgst: Generated<Decimal>;
  taxable: Generated<Decimal>;
  uqc: string | null;
}

export interface Bills {
  amount_paid: Generated<Decimal>;
  bill_date: ColumnType<string, string, string>;
  branch_id: number;
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  due_date: ColumnType<string, string, string>;
  id: Generated<number>;
  igst: Generated<Decimal>;
  internal_no: string;
  is_rcm: Generated<number>;
  journal_entry_id: number | null;
  notes: string | null;
  org_id: number;
  place_of_supply: string;
  round_off: Generated<Decimal>;
  sgst: Generated<Decimal>;
  source_po_id: number | null;
  status: Generated<"draft" | "open" | "overdue" | "paid" | "partially_paid" | "void">;
  subtotal: Generated<Decimal>;
  supply_type: "export_lut" | "export_with_tax" | "inter" | "intra" | "nil_or_exempt" | "sez";
  tds_amount: Generated<Decimal>;
  tds_section: string | null;
  total: Generated<Decimal>;
  updated_at: Generated<Date>;
  vendor_id: number;
  vendor_invoice_no: string;
  voided_at: Date | null;
}

export interface Branches {
  address: string | null;
  created_at: Generated<Date>;
  gstin: string | null;
  id: Generated<number>;
  is_active: Generated<number>;
  is_primary: Generated<number>;
  name: string;
  org_id: number;
  state_code: string;
  updated_at: Generated<Date>;
}

export interface Budgets {
  account_id: number;
  amount: Generated<Decimal>;
  branch_id: Generated<number>;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  fy_label: string;
  id: Generated<number>;
  notes: string | null;
  org_id: number;
  updated_at: Generated<Date>;
}

export interface ChallanLines {
  challan_id: number;
  description: string | null;
  hsn_sac: string | null;
  id: Generated<number>;
  item_id: number | null;
  line_no: number;
  line_total: Generated<Decimal>;
  org_id: number;
  qty: Generated<Decimal>;
  rate: Generated<Decimal>;
  uqc: string | null;
}

export interface Cheques {
  amount: Decimal;
  bank_name: string | null;
  cheque_no: string;
  contact_id: number;
  created_at: Generated<Date>;
  id: Generated<number>;
  is_pdc: Generated<number>;
  kind: "issued" | "received";
  maturity_date: ColumnType<string, string, string>;
  notes: string | null;
  org_id: number;
  payment_id: number | null;
  status: Generated<"bounced" | "cancelled" | "cleared" | "deposited" | "in_hand">;
  updated_at: Generated<Date>;
}

export interface Contacts {
  billing_address: string | null;
  created_at: Generated<Date>;
  credit_limit: Decimal | null;
  display_name: string;
  email: string | null;
  gst_treatment: Generated<"consumer" | "deemed_export" | "overseas" | "registered" | "registered_composition" | "sez" | "sez_developer" | "uin" | "unregistered">;
  gstin: string | null;
  id: Generated<number>;
  is_archived: Generated<number>;
  is_msme: Generated<number>;
  kind: Generated<"both" | "customer" | "vendor">;
  legal_name: string | null;
  msme_udyam_no: string | null;
  notes: string | null;
  opening_balance: Generated<Decimal>;
  org_id: number;
  pan: string | null;
  payment_terms: string | null;
  phone: string | null;
  shipping_address: string | null;
  state_code: string;
  tds_applicable: Generated<number>;
  tds_section: string | null;
  updated_at: Generated<Date>;
}

export interface CreditNoteLines {
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  credit_note_id: number;
  description: string | null;
  discount_pct: Generated<Decimal>;
  gst_rate_pct: Generated<Decimal>;
  hsn_sac: string | null;
  id: Generated<number>;
  igst: Generated<Decimal>;
  item_id: number | null;
  line_no: number;
  line_total: Generated<Decimal>;
  org_id: number;
  qty: Generated<Decimal>;
  rate: Generated<Decimal>;
  sgst: Generated<Decimal>;
  taxable: Generated<Decimal>;
  uqc: string | null;
}

export interface CreditNotes {
  against_invoice_id: number | null;
  applied_amount: Generated<Decimal>;
  branch_id: number;
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  customer_id: number;
  id: Generated<number>;
  igst: Generated<Decimal>;
  journal_entry_id: number | null;
  note_date: ColumnType<string, string, string>;
  number: string;
  org_id: number;
  place_of_supply: string;
  reason: string;
  sgst: Generated<Decimal>;
  status: Generated<"applied" | "open" | "refunded" | "void">;
  subtotal: Generated<Decimal>;
  supply_type: "export_lut" | "export_with_tax" | "inter" | "intra" | "nil_or_exempt" | "sez";
  total: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface CustomFields {
  created_at: Generated<Date>;
  data_type: Generated<"checkbox" | "date" | "number" | "select" | "text">;
  display_order: Generated<number>;
  entity: string;
  field_key: string;
  id: Generated<number>;
  is_active: Generated<number>;
  is_required: Generated<number>;
  label: string;
  options: Json | null;
  org_id: number;
}

export interface CustomFieldValues {
  entity_id: number;
  field_id: number;
  id: Generated<number>;
  org_id: number;
  value: string | null;
}

export interface DeliveryChallans {
  branch_id: number;
  challan_date: ColumnType<string, string, string>;
  challan_type: Generated<"job_work" | "liquid_gas" | "other" | "supply_on_approval">;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  customer_id: number;
  id: Generated<number>;
  notes: string | null;
  number: string;
  org_id: number;
  place_of_supply: string;
  status: Generated<"cancelled" | "invoiced" | "open" | "returned">;
  total: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface Einvoices {
  ack_date: Date | null;
  ack_no: string | null;
  attempts: Generated<number>;
  cancel_reason: string | null;
  cancelled_at: Date | null;
  created_at: Generated<Date>;
  error_code: string | null;
  error_message: string | null;
  id: Generated<number>;
  invoice_id: number;
  irn: string | null;
  org_id: number;
  signed_qr_payload: string | null;
  status: Generated<"cancelled" | "failed" | "not_applicable" | "pending" | "submitted">;
  updated_at: Generated<Date>;
}

export interface EstimateLines {
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  description: string | null;
  discount_pct: Generated<Decimal>;
  estimate_id: number;
  gst_rate_pct: Generated<Decimal>;
  hsn_sac: string | null;
  id: Generated<number>;
  igst: Generated<Decimal>;
  item_id: number | null;
  line_no: number;
  line_total: Generated<Decimal>;
  org_id: number;
  qty: Generated<Decimal>;
  rate: Generated<Decimal>;
  sgst: Generated<Decimal>;
  taxable: Generated<Decimal>;
  uqc: string | null;
}

export interface Estimates {
  branch_id: number;
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  converted_to_id: number | null;
  converted_to_type: string | null;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  customer_id: number;
  estimate_date: ColumnType<string, string, string>;
  expiry_date: ColumnType<string, string, string>;
  id: Generated<number>;
  igst: Generated<Decimal>;
  notes: string | null;
  number: string;
  org_id: number;
  place_of_supply: string;
  sgst: Generated<Decimal>;
  status: Generated<"accepted" | "converted" | "declined" | "draft" | "expired" | "sent">;
  subtotal: Generated<Decimal>;
  supply_type: "export_lut" | "export_with_tax" | "inter" | "intra" | "nil_or_exempt" | "sez";
  total: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface EwayBills {
  challan_id: number | null;
  created_at: Generated<Date>;
  distance_km: number | null;
  error_message: string | null;
  eway_bill_no: string | null;
  from_pincode: string | null;
  generated_at: Date | null;
  id: Generated<number>;
  invoice_id: number | null;
  org_id: number;
  status: Generated<"cancelled" | "expired" | "generated" | "pending">;
  to_pincode: string | null;
  transport_mode: Generated<"air" | "rail" | "road" | "ship">;
  transporter_id: string | null;
  transporter_name: string | null;
  updated_at: Generated<Date>;
  valid_until: Date | null;
  vehicle_no: string | null;
}

export interface Expenses {
  account_id: number;
  amount: Generated<Decimal>;
  billable_customer_id: number | null;
  branch_id: number;
  cgst: Generated<Decimal>;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  expense_date: ColumnType<string, string, string>;
  gst_rate_pct: Generated<Decimal>;
  id: Generated<number>;
  igst: Generated<Decimal>;
  is_billable: Generated<number>;
  itc_eligibility: Generated<"capital_goods" | "eligible" | "ineligible">;
  journal_entry_id: number | null;
  notes: string | null;
  number: string;
  org_id: number;
  paid_through_bank_account_id: number;
  receipt_file_id: number | null;
  reference: string | null;
  sgst: Generated<Decimal>;
  status: Generated<"recorded" | "void">;
  total: Generated<Decimal>;
  updated_at: Generated<Date>;
  vendor_id: number | null;
}

export interface Files {
  attached_to_id: number | null;
  attached_to_type: string | null;
  checksum_sha256: string | null;
  content_type: string;
  created_at: Generated<Date>;
  filename: string;
  id: Generated<number>;
  org_id: number;
  size_bytes: Generated<number>;
  storage_key: string;
  uploaded_by_user_id: number | null;
}

export interface Gstr2bEntries {
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  created_at: Generated<Date>;
  id: Generated<number>;
  igst: Generated<Decimal>;
  invoice_date: ColumnType<string, string, string>;
  invoice_no: string;
  itc_available: Generated<number>;
  match_status: Generated<"matched" | "mismatch" | "missing_in_books" | "unmatched">;
  matched_bill_id: number | null;
  org_id: number;
  return_period: string;
  sgst: Generated<Decimal>;
  taxable: Generated<Decimal>;
  vendor_gstin: string;
  vendor_name: string | null;
}

export interface HsnCodes {
  code: string;
  created_at: Generated<Date>;
  description: string;
  gst_rate_pct: Generated<Decimal>;
  id: Generated<number>;
  is_active: Generated<number>;
  kind: "hsn" | "sac";
  org_id: number;
  updated_at: Generated<Date>;
  uqc: string | null;
}

export interface InvoiceLines {
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  description: string | null;
  discount_pct: Generated<Decimal>;
  gst_rate_pct: Generated<Decimal>;
  hsn_sac: string | null;
  id: Generated<number>;
  igst: Generated<Decimal>;
  invoice_id: number;
  item_id: number | null;
  line_no: number;
  line_total: Generated<Decimal>;
  org_id: number;
  qty: Generated<Decimal>;
  rate: Generated<Decimal>;
  sgst: Generated<Decimal>;
  taxable: Generated<Decimal>;
  uqc: string | null;
}

export interface Invoices {
  adjustment: Generated<Decimal>;
  adjustment_label: string | null;
  amount_paid: Generated<Decimal>;
  branch_id: number;
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  customer_id: number;
  doc_discount: Generated<Decimal>;
  due_date: ColumnType<string, string, string>;
  eway_bill_no: string | null;
  id: Generated<number>;
  igst: Generated<Decimal>;
  invoice_date: ColumnType<string, string, string>;
  journal_entry_id: number | null;
  notes: string | null;
  number: string;
  order_number: string | null;
  org_id: number;
  payment_terms: string | null;
  place_of_supply: string;
  round_off: Generated<Decimal>;
  salesperson_id: number | null;
  sgst: Generated<Decimal>;
  shipping_charge: Generated<Decimal>;
  source_doc_id: number | null;
  source_doc_type: string | null;
  status: Generated<"approved" | "draft" | "overdue" | "paid" | "partially_paid" | "sent" | "void">;
  subject: string | null;
  subtotal: Generated<Decimal>;
  supply_kind: Generated<"both" | "goods" | "service">;
  supply_type: "export_lut" | "export_with_tax" | "inter" | "intra" | "nil_or_exempt" | "sez";
  tcs: Generated<Decimal>;
  terms: string | null;
  total: Generated<Decimal>;
  updated_at: Generated<Date>;
  voided_at: Date | null;
}

export interface Items {
  created_at: Generated<Date>;
  description: string | null;
  gst_rate_pct: Generated<Decimal>;
  hsn_sac: string | null;
  id: Generated<number>;
  is_archived: Generated<number>;
  kind: Generated<"goods" | "service">;
  name: string;
  opening_stock_qty: Decimal | null;
  org_id: number;
  purchase_account_id: number | null;
  purchase_price: Generated<Decimal>;
  reorder_level: Decimal | null;
  sale_account_id: number | null;
  sale_price: Generated<Decimal>;
  sku: string | null;
  tax_pref: Generated<"exempt" | "nil" | "non_gst" | "taxable">;
  track_inventory: Generated<number>;
  updated_at: Generated<Date>;
  uqc: Generated<string>;
}

export interface Jobs {
  attempts: Generated<number>;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  finished_at: Date | null;
  id: Generated<number>;
  kind: string;
  last_error: string | null;
  locked_at: Date | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  org_id: number;
  payload: Json;
  priority: Generated<number>;
  result: Json | null;
  run_after: Date | null;
  started_at: Date | null;
  status: Generated<"cancelled" | "completed" | "failed" | "queued" | "running">;
}

export interface JournalEntries {
  branch_id: number;
  entry_date: ColumnType<string, string, string>;
  entry_no: number;
  id: Generated<number>;
  memo: string | null;
  org_id: number;
  posted_at: Generated<Date>;
  posted_by_user_id: number | null;
  reversal_of_entry_id: number | null;
  source_id: number | null;
  source_type: Generated<string>;
  total_credit: Decimal;
  total_debit: Decimal;
}

export interface JournalLines {
  account_id: number;
  contact_id: number | null;
  credit: Generated<Decimal>;
  debit: Generated<Decimal>;
  description: string | null;
  entry_date: ColumnType<string, string, string>;
  entry_id: number;
  id: Generated<number>;
  line_no: number;
  org_id: number;
}

export interface NumberSeries {
  branch_id: number;
  created_at: Generated<Date>;
  doc_type: string;
  fy_label: string;
  id: Generated<number>;
  next_number: Generated<number>;
  org_id: number;
  padding: Generated<number>;
  prefix: string;
  updated_at: Generated<Date>;
}

export interface Organizations {
  aato_above_5cr: Generated<number>;
  address: string | null;
  base_currency: Generated<string>;
  created_at: Generated<Date>;
  email: string | null;
  fiscal_year_start_month: Generated<number>;
  gst_registration_type: Generated<"composition" | "regular" | "unregistered">;
  id: Generated<number>;
  is_demo: Generated<number>;
  legal_name: string | null;
  logo_file_id: number | null;
  name: string;
  onboarded_at: Date | null;
  pan: string | null;
  phone: string | null;
  updated_at: Generated<Date>;
}

export interface PaymentAllocations {
  amount: Decimal;
  id: Generated<number>;
  org_id: number;
  payment_id: number;
  target_id: number;
  target_type: "bill" | "credit_note" | "invoice" | "retainer" | "vendor_credit";
}

export interface Payments {
  amount: Generated<Decimal>;
  bank_account_id: number;
  bank_charges: Generated<Decimal>;
  branch_id: number;
  contact_id: number;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  id: Generated<number>;
  journal_entry_id: number | null;
  kind: "made" | "received";
  mode: Generated<"card" | "cash" | "cheque" | "imps" | "neft" | "netbanking" | "other" | "rtgs" | "upi">;
  notes: string | null;
  number: string;
  org_id: number;
  payment_date: ColumnType<string, string, string>;
  reference: string | null;
  status: Generated<"cleared" | "void">;
  tds_amount: Generated<Decimal>;
  unapplied_amount: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface PurchaseOrderLines {
  account_id: number | null;
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  description: string | null;
  discount_pct: Generated<Decimal>;
  gst_rate_pct: Generated<Decimal>;
  hsn_sac: string | null;
  id: Generated<number>;
  igst: Generated<Decimal>;
  item_id: number | null;
  line_no: number;
  line_total: Generated<Decimal>;
  org_id: number;
  purchase_order_id: number;
  qty: Generated<Decimal>;
  rate: Generated<Decimal>;
  sgst: Generated<Decimal>;
  taxable: Generated<Decimal>;
  uqc: string | null;
}

export interface PurchaseOrders {
  billed_amount: Generated<Decimal>;
  branch_id: number;
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  expected_date: ColumnType<string | null, string | null, string | null>;
  id: Generated<number>;
  igst: Generated<Decimal>;
  notes: string | null;
  number: string;
  order_date: ColumnType<string, string, string>;
  org_id: number;
  place_of_supply: string;
  sgst: Generated<Decimal>;
  status: Generated<"billed" | "cancelled" | "closed" | "draft" | "open" | "partially_billed">;
  subtotal: Generated<Decimal>;
  supply_type: "export_lut" | "export_with_tax" | "inter" | "intra" | "nil_or_exempt" | "sez";
  total: Generated<Decimal>;
  updated_at: Generated<Date>;
  vendor_id: number;
}

export interface RecurringInvoices {
  auto_send: Generated<number>;
  branch_id: number;
  created_at: Generated<Date>;
  customer_id: number;
  end_date: ColumnType<string | null, string | null, string | null>;
  frequency: Generated<"monthly" | "quarterly" | "weekly" | "yearly">;
  id: Generated<number>;
  is_active: Generated<number>;
  last_generated_at: ColumnType<string | null, string | null, string | null>;
  next_run: ColumnType<string, string, string>;
  org_id: number;
  payment_terms: string | null;
  profile_name: string;
  start_date: ColumnType<string, string, string>;
  template: Json;
  updated_at: Generated<Date>;
}

export interface RecurringJournals {
  amount: Decimal;
  branch_id: number;
  created_at: Generated<Date>;
  credit_account_id: number;
  debit_account_id: number;
  end_date: ColumnType<string | null, string | null, string | null>;
  frequency: Generated<"monthly" | "quarterly" | "yearly">;
  id: Generated<number>;
  is_active: Generated<number>;
  last_posted_at: ColumnType<string | null, string | null, string | null>;
  memo: string | null;
  name: string;
  next_run: ColumnType<string, string, string>;
  org_id: number;
  updated_at: Generated<Date>;
}

export interface RetainerInvoices {
  amount: Generated<Decimal>;
  amount_paid: Generated<Decimal>;
  applied_amount: Generated<Decimal>;
  branch_id: number;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  customer_id: number;
  description: string;
  id: Generated<number>;
  journal_entry_id: number | null;
  number: string;
  org_id: number;
  retainer_date: ColumnType<string, string, string>;
  status: Generated<"applied" | "draft" | "paid" | "partially_applied" | "sent" | "void">;
  updated_at: Generated<Date>;
}

export interface SalesOrderLines {
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  description: string | null;
  discount_pct: Generated<Decimal>;
  gst_rate_pct: Generated<Decimal>;
  hsn_sac: string | null;
  id: Generated<number>;
  igst: Generated<Decimal>;
  item_id: number | null;
  line_no: number;
  line_total: Generated<Decimal>;
  org_id: number;
  qty: Generated<Decimal>;
  rate: Generated<Decimal>;
  sales_order_id: number;
  sgst: Generated<Decimal>;
  taxable: Generated<Decimal>;
  uqc: string | null;
}

export interface SalesOrders {
  branch_id: number;
  cess: Generated<Decimal>;
  cgst: Generated<Decimal>;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  customer_id: number;
  expected_ship_date: ColumnType<string | null, string | null, string | null>;
  id: Generated<number>;
  igst: Generated<Decimal>;
  invoiced_amount: Generated<Decimal>;
  number: string;
  order_date: ColumnType<string, string, string>;
  org_id: number;
  place_of_supply: string;
  sgst: Generated<Decimal>;
  source_estimate_id: number | null;
  status: Generated<"cancelled" | "closed" | "invoiced" | "open" | "partially_invoiced">;
  subtotal: Generated<Decimal>;
  supply_type: "export_lut" | "export_with_tax" | "inter" | "intra" | "nil_or_exempt" | "sez";
  total: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface SchemaMigrations {
  applied_at: Generated<Date>;
  checksum: string;
  duration_ms: Generated<number>;
  filename: string;
}

export interface Sequences {
  name: string;
  next_value: Generated<number>;
  org_id: number;
  updated_at: Generated<Date>;
}

export interface Sessions {
  active_branch_id: number | null;
  created_at: Generated<Date>;
  expires_at: Date;
  ip: string | null;
  last_seen_at: Date | null;
  org_id: number;
  revoked_at: Date | null;
  token_hash: string;
  user_agent: string | null;
  user_id: number;
}

export interface Settings {
  org_id: number;
  scope: string;
  setting_key: string;
  updated_at: Generated<Date>;
  updated_by_user_id: number | null;
  value: Json;
}

export interface StockAdjustments {
  adjust_date: ColumnType<string, string, string>;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  id: Generated<number>;
  item_id: number;
  journal_entry_id: number | null;
  notes: string | null;
  org_id: number;
  qty_delta: Decimal;
  reason: Generated<"damage" | "expiry" | "opening" | "other" | "sample" | "stocktake" | "theft">;
  warehouse_id: number | null;
}

export interface TransactionLocks {
  id: Generated<number>;
  locked_by_user_id: number | null;
  locked_upto: ColumnType<string | null, string | null, string | null>;
  module: "accountant" | "banking" | "purchases" | "sales";
  org_id: number;
  reason: string | null;
  updated_at: Generated<Date>;
}

export interface UserBranches {
  branch_id: number;
  user_id: number;
}

export interface Users {
  created_at: Generated<Date>;
  email: string;
  failed_logins: Generated<number>;
  home_branch_id: number | null;
  id: Generated<number>;
  is_active: Generated<number>;
  last_login_at: Date | null;
  locked_until: Date | null;
  name: string;
  org_id: number;
  password_hash: string | null;
  phone: string | null;
  role: Generated<"accountant" | "admin" | "sales" | "staff" | "viewer">;
  updated_at: Generated<Date>;
}

export interface VendorCredits {
  against_bill_id: number | null;
  applied_amount: Generated<Decimal>;
  branch_id: number;
  created_at: Generated<Date>;
  created_by_user_id: number | null;
  credit_date: ColumnType<string, string, string>;
  id: Generated<number>;
  journal_entry_id: number | null;
  number: string;
  org_id: number;
  reason: string;
  status: Generated<"applied" | "open" | "refunded" | "void">;
  total: Generated<Decimal>;
  updated_at: Generated<Date>;
  vendor_id: number;
}

export interface Warehouses {
  address: string | null;
  branch_id: number | null;
  code: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  is_active: Generated<number>;
  is_primary: Generated<number>;
  name: string;
  org_id: number;
  updated_at: Generated<Date>;
}

export interface WorkflowRules {
  actions: Json;
  conditions: Json | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  is_active: Generated<number>;
  name: string;
  org_id: number;
  trigger_event: string;
  updated_at: Generated<Date>;
}

export interface DB {
  accounts: Accounts;
  api_tokens: ApiTokens;
  approval_rules: ApprovalRules;
  audit_log: AuditLog;
  bank_accounts: BankAccounts;
  bank_rules: BankRules;
  bank_statement_imports: BankStatementImports;
  bank_transactions: BankTransactions;
  bank_transfers: BankTransfers;
  bill_lines: BillLines;
  bills: Bills;
  branches: Branches;
  budgets: Budgets;
  challan_lines: ChallanLines;
  cheques: Cheques;
  contacts: Contacts;
  credit_note_lines: CreditNoteLines;
  credit_notes: CreditNotes;
  custom_field_values: CustomFieldValues;
  custom_fields: CustomFields;
  delivery_challans: DeliveryChallans;
  einvoices: Einvoices;
  estimate_lines: EstimateLines;
  estimates: Estimates;
  eway_bills: EwayBills;
  expenses: Expenses;
  files: Files;
  gstr2b_entries: Gstr2bEntries;
  hsn_codes: HsnCodes;
  invoice_lines: InvoiceLines;
  invoices: Invoices;
  items: Items;
  jobs: Jobs;
  journal_entries: JournalEntries;
  journal_lines: JournalLines;
  number_series: NumberSeries;
  organizations: Organizations;
  payment_allocations: PaymentAllocations;
  payments: Payments;
  purchase_order_lines: PurchaseOrderLines;
  purchase_orders: PurchaseOrders;
  recurring_invoices: RecurringInvoices;
  recurring_journals: RecurringJournals;
  retainer_invoices: RetainerInvoices;
  sales_order_lines: SalesOrderLines;
  sales_orders: SalesOrders;
  schema_migrations: SchemaMigrations;
  sequences: Sequences;
  sessions: Sessions;
  settings: Settings;
  stock_adjustments: StockAdjustments;
  transaction_locks: TransactionLocks;
  user_branches: UserBranches;
  users: Users;
  vendor_credits: VendorCredits;
  warehouses: Warehouses;
  workflow_rules: WorkflowRules;
}
